title: 'notmudge.github.io'
description: "Ooga Booga"
baseurl: "/"
url: "https://notmudge.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: 'follow us on <a href="https://www.kaggle.com/alexmudge">Kaggle Placeholder</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
