title: 'notmudge.github.io'
description: "Ooga Booga"
baseurl: "jekyll-theme-console-demo-hacker"
url: "https://notmudge.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
